# Generated by Django 5.2.4 on 2025-09-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcm_token',
        ),
    ]
