# Generated by Django 5.2.4 on 2025-09-13 08:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_user_fcm_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone',
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='club',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
