# Generated by Django 5.2.4 on 2025-09-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_rating_venue_ratings_remove_venue_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
