# Generated by Django 5.2.4 on 2025-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_venue_closing_time_alter_venue_opening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='slots',
            field=models.ManyToManyField(related_name='bookings', to='API.slot'),
        ),
    ]
