# Generated by Django 5.2.4 on 2025-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_booking_slot_booking_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
