# Generated by Django 5.2.4 on 2025-09-25 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_booking_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_venues', to='API.user')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='API.venue')),
            ],
            options={
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
